[project]
name = "strava-art"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gpxpy>=1.6.2",
    "selenium==4.24.0",
    "streamlit-folium>=0.22.0",
    "streamlit>=1.38.0",
]
